### ISSUE TITLE
gradient computation

### ISSUE THREAD

**Issue by kmatzen** [jhjin/triplet-criterion#2]
I have a question about the implementation of the gradient in this code.  This seems like the correct gradient for dL/da, but does not seem to include dL/dp or dL/dn.  Is this a mistake or did you find it to perform better in practice if the positive and negative are held fixed while only the anchor moves?

https://github.com/jhjin/triplet-criterion/blob/master/TripletCriterion.lua#L144

**Comment by jhjin** [comment]
@kmatzen I intended to fix the positives and negatives while training, which does not include  dL/dp or dL/dn as you pointed out. It was difficult to make the training converge to desirable accuracy and using the modification works better in my case.

**Comment by kmatzen** [comment]
Thanks for the insight!
