### ISSUE TITLE
cannot convert 'struct THFloatTensor *' to  'struct THCudaTensor *'

### ISSUE THREAD

**Issue by alecwangcq** [jhjin/triplet-criterion#6]
Hi there, I encounter with errors like the followings.. And when I use other loss criterion, there is no errors...
I also tried to deal with it: before the tensor is passed into TripletCriterion, I cast the Tensor to be CudaTensor, like  target:typeAs(torch.CudaTensor())
but it did not work, the same error still occurs. 

```
/home/haha/torch/install/bin/luajit: ...torch/install/share/lua/5.1/triplet/TripletCriterion.lua:55: 
bad argument #8 to 'updateOutput' (cannot convert 'struct THFloatTensor *' to
 'struct THCudaTensor *')
```

```
/home/haha/torch/install/bin/luajit: ...torch/install/share/lua/5.1/triplet/TripletCriterion.lua:55: 
bad argument #3 to 'updateOutput' (cannot convert 'struct THCudaLongTensor *' to
 'struct THCudaTensor *')
```

**Comment by jhjin** [comment]
How different is your code from the testing code ? https://github.com/jhjin/triplet-criterion/blob/master/test.lua Could you share your code to reproduce the error? It seems that the Triplet instance is not casted to CUDA.

**Comment by alecwangcq** [comment]
I printed the instance:type(), it was CudaLongTensor.
But this error was solved by updating torch, torch, cutorch, cudnn, cunn to the latest version. 
Anyway, thanks a lot.
